### ISSUE TITLE
Error trying to queue 3450 songs at once

### ISSUE THREAD

**Issue by thejoshwolfe** [andrewrk/groovebasin#413]
Is fragmented messages just not supported in yawl or something?

```
web socket error: Error: fragmented messages not allowed
    at failConnection (/home/josh/dev/groovebasin/node_modules/yawl/index.js:848:13)
    at WebSocketClient._transform (/home/josh/dev/groovebasin/node_modules/yawl/index.js:448:13)
    at WebSocketClient.Transform._read (_stream_transform.js:179:10)
    at WebSocketClient.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at WebSocketClient.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at CleartextStream.pipeOnReadable (_stream_readable.js:642:5)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at _stream_readable.js:419:7
```

**Comment by andrewrk** [comment]
Interesting. They're supported but I did not realize the HTML websocket API would automatically change the type of large messages to fragmented. This is easily solved.
