### ISSUE TITLE
crash while uploading songs

### ISSUE THREAD

**Issue by thejoshwolfe** [andrewrk/groovebasin#420]
my server is really old and slow. while uploading several songs at once, groovebasin crashed with this error:

```
/home/josh/dev/groovebasin/lib/player.js:507
    self.grooveEncoder.detach(function(err) {
                       ^
Error: detach: not attached
    at startEncoderDetach (/home/josh/dev/groovebasin/lib/player.js:507:24)
    at Player.detachEncoder (/home/josh/dev/groovebasin/lib/player.js:631:3)
    at timeout [as _onTimeout] (/home/josh/dev/groovebasin/lib/player.js:942:12)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by andrewrk** [comment]
Is there anything in the log before that, such as "encoder attach failed"?

**Comment by thejoshwolfe** [comment]
http://pastebin.com/0bAhqDfy

**Comment by andrewrk** [comment]
I don't have a lot of confidence that it is fixed, but I also don't see how this problem could happen. If it happens again, re-open and then I'll add a try/catch for the `detach: not attached` error.
