### ISSUE TITLE
crash when removing songs from playlist

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/groovebasin#453]
609d4c0f45f745db1d73ed49f18700c4d16ed8a4

```
/home/groovebasin/groovebasin/lib/player_server.js:1730
    trackKey: playlistForEvent.items[itemKey].key,
                              ^
TypeError: Cannot read property 'items' of undefined
    at PlayerServer.playlistRemoveItems (/home/groovebasin/groovebasin/lib/player_server.js:1730:31)
    at Object.actions.playlistRemoveItems.fn (/home/groovebasin/groovebasin/lib/player_server.js:379:12)
    at WebSocketApiClient.onMessage (/home/groovebasin/groovebasin/lib/player_server.js:1047:12)
    at WebSocketApiClient.emit (events.js:110:17)
    at WebSocketClient.<anonymous> (/home/groovebasin/groovebasin/lib/web_socket_api_client.js:36:10)
    at WebSocketClient.emit (events.js:107:17)
    at WebSocketClient._transform (/home/groovebasin/groovebasin/node_modules/yawl/index.js:544:16)
    at WebSocketClient.Transform._read (_stream_transform.js:179:10)
    at WebSocketClient.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

**Comment by saintger** [comment]
Perhaps it is related to the issue with MPD protocol when I am removing a song:
https://github.com/andrewrk/groovebasin/issues/411

**Comment by andrewrk** [comment]
a07d3e0379

```
Error deleting files: Error: ENOENT, unlink '/home/groovebasin/music/Pitbull - Timber ft. Ke$ha.mp4'
    at Error (native)
labels: { '9GwKNV-W6NHdtSaDqPb5ZdR_NJliZJz1': { name: 'pirate music', color: '#bfdadc' } }
/home/groovebasin/groovebasin/lib/player_server.js:1946
    trackKey: playlistForEvent.items[itemKey].key,
                              ^
TypeError: Cannot read property 'items' of undefined
    at PlayerServer.playlistRemoveItems (/home/groovebasin/groovebasin/lib/player_server.js:1946:31)
    at Object.actions.playlistRemoveItems.fn (/home/groovebasin/groovebasin/lib/player_server.js:384:12)
    at WebSocketApiClient.onMessage (/home/groovebasin/groovebasin/lib/player_server.js:1157:12)
    at WebSocketApiClient.emit (events.js:110:17)
    at WebSocketClient.<anonymous> (/home/groovebasin/groovebasin/lib/web_socket_api_client.js:36:10)
    at WebSocketClient.emit (events.js:107:17)
    at WebSocketClient._transform (/home/groovebasin/groovebasin/node_modules/yawl/index.js:544:16)
    at WebSocketClient.Transform._read (_stream_transform.js:179:10)
```
