### ISSUE TITLE
Issues installing with binding

### ISSUE THREAD

**Issue by samjaninf** [andrewrk/groovebasin#481]
After having several setbacks, I've finally gotten to the final command, ```npm start``` that is where I get stuck. This happens:

```
> groovebasin@1.5.1 start /opt/groovebasin
> node lib/server.js

/opt/groovebasin/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /opt/groovebasin/node_modules/groove/build/groove.node
 → /opt/groovebasin/node_modules/groove/build/Debug/groove.node
 → /opt/groovebasin/node_modules/groove/build/Release/groove.node
 → /opt/groovebasin/node_modules/groove/out/Debug/groove.node
 → /opt/groovebasin/node_modules/groove/Debug/groove.node
 → /opt/groovebasin/node_modules/groove/out/Release/groove.node
 → /opt/groovebasin/node_modules/groove/Release/groove.node
 → /opt/groovebasin/node_modules/groove/build/default/groove.node
 → /opt/groovebasin/node_modules/groove/compiled/5.2.0/linux/x64/groove.node
    at bindings (/opt/groovebasin/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/opt/groovebasin/node_modules/groove/lib/index.js:1:35)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/opt/groovebasin/lib/player.js:1:14)
    at Module._compile (module.js:399:26)

npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! groovebasin@1.5.1 start: `node lib/server.js`
npm ERR! Exit status 1
```

The groove.node file doesn't seem to be getting made. Any help would be greatly appreciated.

My issues aside, great project. Love the idea of it. Can't wait for 5.0.0.

**Comment by andrewrk** [comment]
are you running from source or from a package?

**Comment by samjaninf** [comment]
I am running it from source. through git clone of this repo.

**Comment by andrewrk** [comment]
Did you `npm install` before starting the server?

**Comment by samjaninf** [comment]
Yep. Same exact issue.

**Comment by andrewrk** [comment]
What is the current working directory you're running the commands from? is there a node_modules/ directory there?

You have the groovebasin source code cloned to /opt/groovebasin?

**Comment by andrewrk** [comment]
What is the `start` command? Is that some kind of process monitoring daemon? Does it work if you run it without that? (Not saying you can't use one, just for troubleshooting purposes)

**Comment by samjaninf** [comment]
CWD is ```/opt/groovebasin```.

The start command is from your docs, I do ```npm start``` and that's the output I get.

**Comment by andrewrk** [comment]
Did the build succeed? If the build succeeded, one of those files listed should exist:

```
 → /opt/groovebasin/node_modules/groove/build/groove.node
 → /opt/groovebasin/node_modules/groove/build/Debug/groove.node
 → /opt/groovebasin/node_modules/groove/build/Release/groove.node
 → /opt/groovebasin/node_modules/groove/out/Debug/groove.node
 → /opt/groovebasin/node_modules/groove/Debug/groove.node
 → /opt/groovebasin/node_modules/groove/out/Release/groove.node
 → /opt/groovebasin/node_modules/groove/Release/groove.node
 → /opt/groovebasin/node_modules/groove/build/default/groove.node
 → /opt/groovebasin/node_modules/groove/compiled/5.2.0/linux/x64/groove.node
```

Is one of these files present? If `groove.node` doesn't exist somewhere in node_modules/groove/* then the build didn't succeed.

**Comment by samjaninf** [comment]
This is the output I get from ```npm run build```:

```tuvok@tuvok:/opt/groovebasin# npm run build

> groovebasin@1.5.1 build /opt/groovebasin
> npm install && ./build

npm WARN prefer global node-gyp@3.2.1 should be installed with -g
npm WARN lifecycle groove@2.5.0~install: cannot run in wd %s %s (wd=%s) groove@2.5.0 node-gyp rebuild /opt/groovebasin/node_modules/groove

> leveldown@1.4.3 install /opt/groovebasin/node_modules/leveldown
> prebuild --download

groovebasin@1.5.1 /opt/groovebasin
├── browserify-lite@0.2.5 
├─┬ connect-static@1.5.1 
│ ├── mime@1.2.11 
│ └── streamsink@1.2.0 
├── content-disposition@0.5.0 
├─┬ cookies@0.5.1 
│ └── keygrip@1.0.1 
├── curlydiff@2.0.1 
├─┬ express@4.12.4 
│ ├─┬ accepts@1.2.13 
│ │ ├─┬ mime-types@2.1.8 
│ │ │ └── mime-db@1.20.0 
│ │ └── negotiator@0.5.3 
│ ├── content-type@1.0.1 
│ ├── cookie@0.1.2 
│ ├── cookie-signature@1.0.6 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── depd@1.0.1 
│ ├── escape-html@1.0.1 
│ ├─┬ etag@1.6.0 
│ │ └── crc@3.2.1 
│ ├── finalhandler@0.3.6 
│ ├── fresh@0.2.4 
│ ├── merge-descriptors@1.0.0 
│ ├── methods@1.1.1 
│ ├─┬ on-finished@2.2.1 
│ │ └── ee-first@1.1.0 
│ ├── parseurl@1.3.0 
│ ├── path-to-regexp@0.1.3 
│ ├─┬ proxy-addr@1.0.10 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.0.5 
│ ├── qs@2.4.2 
│ ├── range-parser@1.0.3 
│ ├─┬ send@0.12.3 
│ │ ├── destroy@1.0.3 
│ │ └── mime@1.3.4 
│ ├─┬ type-is@1.6.10 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.0 
│ └── vary@1.0.1 
├── findit2@2.2.3 
├─┬ googleapis@2.0.6 
│ ├── async@0.9.2 
│ ├─┬ gapitoken@0.1.5 
│ │ └─┬ jws@3.0.0 
│ │   ├─┬ base64url@1.0.5 
│ │   │ ├─┬ concat-stream@1.4.10 
│ │   │ │ └── typedarray@0.0.6 
│ │   │ └─┬ meow@2.0.0 
│ │   │   ├─┬ camelcase-keys@1.0.0 
│ │   │   │ ├── camelcase@1.2.1 
│ │   │   │ └── map-obj@1.0.1 
│ │   │   ├─┬ indent-string@1.2.2 
│ │   │   │ ├── get-stdin@4.0.1 
│ │   │   │ └─┬ repeating@1.1.3 
│ │   │   │   └─┬ is-finite@1.0.1 
│ │   │   │     └── number-is-nan@1.0.0 
│ │   │   └── object-assign@1.0.0 
│ │   └─┬ jwa@1.0.2 
│ │     ├── base64url@0.0.6 
│ │     ├── buffer-equal-constant-time@1.0.1 
│ │     └─┬ ecdsa-sig-formatter@1.0.2 
│ │       ├─┬ asn1.js@2.2.1 
│ │       │ ├── bn.js@2.2.0 
│ │       │ └── minimalistic-assert@1.0.0 
│ │       └── base64-url@1.2.1 
│ ├─┬ google-auth-library@0.9.7 
│ │ ├── async@1.4.2 
│ │ ├─┬ gtoken@1.2.0 
│ │ │ ├─┬ google-p12-pem@0.1.0 
│ │ │ │ └── node-forge@0.6.38 
│ │ │ └─┬ request@2.67.0 
│ │ │   ├── aws-sign2@0.6.0 
│ │ │   ├─┬ bl@1.0.0 
│ │ │   │ └── readable-stream@2.0.5 
│ │ │   ├── caseless@0.11.0 
│ │ │   ├─┬ combined-stream@1.0.5 
│ │ │   │ └── delayed-stream@1.0.0 
│ │ │   ├─┬ form-data@1.0.0-rc3 
│ │ │   │ └── async@1.5.1 
│ │ │   ├─┬ har-validator@2.0.3 
│ │ │   │ └─┬ pinkie-promise@2.0.0 
│ │ │   │   └── pinkie@2.0.1 
│ │ │   ├── hawk@3.1.2 
│ │ │   ├─┬ http-signature@1.1.0 
│ │ │   │ ├─┬ jsprim@1.2.2 
│ │ │   │ │ ├── extsprintf@1.0.2 
│ │ │   │ │ ├── json-schema@0.2.2 
│ │ │   │ │ └── verror@1.3.6 
│ │ │   │ └─┬ sshpk@1.7.1 
│ │ │   │   ├── asn1@0.2.3 
│ │ │   │   ├── assert-plus@0.2.0 
│ │ │   │   ├── dashdash@1.11.0 
│ │ │   │   ├── ecc-jsbn@0.1.1 
│ │ │   │   ├── jodid25519@1.0.2 
│ │ │   │   ├── jsbn@0.1.0 
│ │ │   │   └── tweetnacl@0.13.2 
│ │ │   ├── is-typedarray@1.0.0 
│ │ │   ├── oauth-sign@0.8.0 
│ │ │   └── qs@5.2.0 
│ │ ├── lodash.noop@3.0.0 
│ │ └─┬ request@2.60.0 
│ │   ├─┬ bl@1.0.0 
│ │   │ └── readable-stream@2.0.5 
│ │   ├── caseless@0.11.0 
│ │   ├─┬ combined-stream@1.0.5 
│ │   │ └── delayed-stream@1.0.0 
│ │   ├── extend@3.0.0 
│ │   ├── form-data@1.0.0-rc3 
│ │   ├── hawk@3.1.2 
│ │   ├── http-signature@0.11.0 
│ │   ├── oauth-sign@0.8.0 
│ │   └── qs@4.0.0 
│ ├─┬ request@2.54.0 
│ │ ├── aws-sign2@0.5.0 
│ │ ├── caseless@0.9.0 
│ │ ├─┬ combined-stream@0.0.7 
│ │ │ └── delayed-stream@0.0.5 
│ │ ├── forever-agent@0.6.1 
│ │ ├─┬ form-data@0.2.0 
│ │ │ └─┬ mime-types@2.0.14 
│ │ │   └── mime-db@1.12.0 
│ │ ├─┬ har-validator@1.8.0 
│ │ │ ├── bluebird@2.10.2 
│ │ │ ├─┬ chalk@1.1.1 
│ │ │ │ ├── ansi-styles@2.1.0 
│ │ │ │ ├── escape-string-regexp@1.0.4 
│ │ │ │ ├─┬ has-ansi@2.0.0 
│ │ │ │ │ └── ansi-regex@2.0.0 
│ │ │ │ ├── strip-ansi@3.0.0 
│ │ │ │ └── supports-color@2.0.0 
│ │ │ ├─┬ commander@2.9.0 
│ │ │ │ └── graceful-readlink@1.0.1 
│ │ │ └─┬ is-my-json-valid@2.12.3 
│ │ │   ├── generate-function@2.0.0 
│ │ │   ├─┬ generate-object-property@1.2.0 
│ │ │   │ └── is-property@1.0.2 
│ │ │   └── jsonpointer@2.0.0 
│ │ ├─┬ hawk@2.3.1 
│ │ │ ├── boom@2.10.1 
│ │ │ ├── cryptiles@2.0.5 
│ │ │ ├── hoek@2.16.3 
│ │ │ └── sntp@1.0.9 
│ │ ├─┬ http-signature@0.10.1 
│ │ │ ├── asn1@0.1.11 
│ │ │ ├── assert-plus@0.1.5 
│ │ │ └── ctype@0.5.3 
│ │ ├── isstream@0.1.2 
│ │ ├── json-stringify-safe@5.0.1 
│ │ ├─┬ mime-types@2.0.14 
│ │ │ └── mime-db@1.12.0 
│ │ ├── node-uuid@1.4.7 
│ │ ├── oauth-sign@0.6.0 
│ │ ├── stringstream@0.0.5 
│ │ ├── tough-cookie@2.2.1 
│ │ └── tunnel-agent@0.4.2 
│ └── string-template@0.2.1 
├─┬ groove@2.5.0 
│ ├── bindings@1.2.1 
│ └── nan@2.1.0 
├── httpolyglot@0.1.1 
├── human-size@1.1.0 
├── keese@1.1.1 
├─┬ lastfm@0.9.2 
│ └── underscore@1.6.0 
├─┬ leveldown@1.4.3 
│ ├─┬ abstract-leveldown@2.4.1 
│ │ └── xtend@4.0.1 
│ ├── fast-future@1.0.1 
│ └─┬ prebuild@2.8.1 
│   ├── async@1.5.1 
│   ├── expand-template@1.0.2 
│   ├─┬ ghreleases@1.0.4 
│   │ ├── after@0.8.1 
│   │ ├── ghrepos@2.0.0 
│   │ ├─┬ ghutils@3.2.0 
│   │ │ └─┬ jsonist@1.2.0 
│   │ │   ├─┬ bl@1.0.0 
│   │ │   │ └── readable-stream@2.0.5 
│   │ │   └─┬ hyperquest@1.2.0 
│   │ │     ├── duplexer2@0.0.2 
│   │ │     └─┬ through2@0.6.5 
│   │ │       └── readable-stream@1.0.33 
│   │ ├── simple-mime@0.1.0 
│   │ └── url-template@2.0.6 
│   ├── github-from-package@0.0.0 
│   ├── home-dir@1.0.0 
│   ├── minimist@1.2.0 
│   ├─┬ node-gyp@3.2.1 
│   │ ├── fstream@1.0.8 
│   │ ├─┬ glob@4.5.3 
│   │ │ ├── inflight@1.0.4 
│   │ │ └─┬ minimatch@2.0.10 
│   │ │   └─┬ brace-expansion@1.1.2 
│   │ │     ├── balanced-match@0.3.0 
│   │ │     └── concat-map@0.0.1 
│   │ ├── graceful-fs@4.1.2 
│   │ ├── minimatch@1.0.0 
│   │ ├─┬ nopt@3.0.6 
│   │ │ └── abbrev@1.0.7 
│   │ ├── npmlog@1.2.1 
│   │ ├─┬ path-array@1.0.0 
│   │ │ └── array-index@0.1.1 
│   │ ├─┬ rimraf@2.5.0 
│   │ │ └─┬ glob@6.0.3 
│   │ │   ├── minimatch@3.0.0 
│   │ │   └── path-is-absolute@1.0.0 
│   │ ├─┬ tar@2.2.1 
│   │ │ └── block-stream@0.0.8 
│   │ └─┬ which@1.2.1 
│   │   └─┬ is-absolute@0.1.7 
│   │     └── is-relative@0.1.3 
│   ├─┬ npmlog@2.0.0 
│   │ ├── ansi@0.3.0 
│   │ ├─┬ are-we-there-yet@1.0.5 
│   │ │ ├── delegates@0.1.0 
│   │ │ └── readable-stream@1.1.13 
│   │ └─┬ gauge@1.2.2 
│   │   ├── has-unicode@1.0.1 
│   │   ├─┬ lodash.pad@3.1.1 
│   │   │ ├── lodash._basetostring@3.0.1 
│   │   │ └─┬ lodash._createpadding@3.6.1 
│   │   │   └── lodash.repeat@3.0.1 
│   │   ├── lodash.padleft@3.1.1 
│   │   └── lodash.padright@3.1.1 
│   ├─┬ pump@1.0.1 
│   │ ├── end-of-stream@1.1.0 
│   │ └─┬ once@1.3.3 
│   │   └── wrappy@1.0.1 
│   ├─┬ rc@1.1.6 
│   │ ├── deep-extend@0.4.0 
│   │ ├── ini@1.3.4 
│   │ └── strip-json-comments@1.0.4 
│   ├─┬ simple-get@1.4.3 
│   │ └── unzip-response@1.0.0 
│   ├── tar-fs@1.9.0 
│   └─┬ tar-stream@1.3.1 
│     ├── bl@1.0.0 
│     └─┬ readable-stream@2.0.5 
│       ├── process-nextick-args@1.0.6 
│       └── util-deprecate@1.0.2 
├── mess@0.1.2 
├─┬ mkdirp@0.5.1 
│ └── minimist@0.0.8 
├─┬ multiparty@4.1.2 
│ └── fd-slicer@1.0.1 
├─┬ music-library-index@2.1.0 
│ └── diacritics@1.2.3 
├─┬ mv@2.0.3 
│ ├── ncp@0.6.0 
│ └── rimraf@2.2.8 
├─┬ osenv@0.1.3 
│ ├── os-homedir@1.0.1 
│ └── os-tmpdir@1.0.1 
├── pend@1.2.0 
├── semver@4.3.6 
├── serve-static@1.9.3 
├─┬ stylus@0.49.3 
│ ├── css-parse@1.7.0 
│ ├─┬ glob@3.2.11 
│ │ ├── inherits@2.0.1 
│ │ └─┬ minimatch@0.3.0 
│ │   ├── lru-cache@2.7.3 
│ │   └── sigmund@1.0.1 
│ ├── mkdirp@0.3.5 
│ ├── sax@0.5.8 
│ └─┬ source-map@0.1.43 
│   └── amdefine@1.0.0 
├── yauzl@2.3.1 
├─┬ yawl@1.0.2 
│ └─┬ bl@0.9.4 
│   └─┬ readable-stream@1.0.33 
│     ├── core-util-is@1.0.2 
│     ├── isarray@0.0.1 
│     └── string_decoder@0.10.31 
├─┬ yazl@2.2.2 
│ └── buffer-crc32@0.2.5 
└─┬ ytdl-core@0.7.9 
  ├── html-entities@1.2.0 
  ├─┬ jstream@0.2.8 
  │ └── clarinet@0.11.0 
  └── sax@1.1.4 

  compiled public/app.css
```

Still get the same errors though.

**Comment by andrewrk** [comment]
This seems like a problem:

```
npm WARN lifecycle groove@2.5.0~install: cannot run in wd %s %s (wd=%s) groove@2.5.0 node-gyp rebuild /opt/groovebasin/node_modules/groove
```

This tells me that the `npm install` of groove module didn't work. I'm not sure what "wd" means. Maybe "working directory"?

Are you running as root? That's probably not a good idea. My suggestion is to either run groovebasin as its own user with its own /home/foo directory with the music in there, or if your music is in /home/you/music or similar, run groovebasin as your own user, from your own home directory.

**Comment by samjaninf** [comment]
That seems, to have done it!
Never seen that error before and I just installed about 5 node projects right before that.
Next, let's see if I can't have it connect to a an NFS volume over the internet.
Anyways,
Thank you a TON! Good Luck!

**Comment by andrewrk** [comment]
Glad you got it working. Cheers!
