### ISSUE TITLE
NPM compilation problems

### ISSUE THREAD

**Issue by WouterLVV** [andrewrk/groovebasin#482]
After a lot of struggling with libgroove and the like, I got the following error during build:

make: Entering directory '.../groovebasin-1.5.1/node_modules/groove/build'
  CXX(target) Release/obj.target/groove/src/groove.o
../src/groove.cc: In function ‘void Initialize(v8::Handle<v8::Object>)’:
../src/groove.cc:61:17: error: ‘groove_init’ was not declared in this scope
     groove_init();
                 ^
../src/groove.cc:62:12: error: ‘groove_finish’ was not declared in this scope
     atexit(groove_finish);
            ^
../src/groove.cc:81:45: error: ‘GROOVE_EVERY_SINK_FULL’ was not declared in this scope
     SetProperty(exports, "EVERY_SINK_FULL", GROOVE_EVERY_SINK_FULL);
                                             ^
../src/groove.cc:82:43: error: ‘GROOVE_ANY_SINK_FULL’ was not declared in this scope
     SetProperty(exports, "ANY_SINK_FULL", GROOVE_ANY_SINK_FULL);
                                           ^
groove.target.mk:96: recipe for target 'Release/obj.target/groove/src/groove.o' failed
make: *** [Release/obj.target/groove/src/groove.o] Error 1
make: Leaving directory '/home/wouter/groove/libgroove2/groovebasin-1.5.1/node_modules/groove/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Linux 4.2.0-23-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wouter/groove/libgroove2/groovebasin-1.5.1/node_modules/groove
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.2.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

This even occurred was on a clean clone (as I've been trying to install 1.5.1 for two days now, so thing have become a little messy sometimes).
The packages I have installed as support are:

ii  groovebasin   1.4.0-1
ii  libgroove-dbg:amd64
ii  libgroove-dev:amd64
ii  libgroove4:amd64
ii  libgroovefingerprinter-dev:amd64
ii  libgrooveloudness-dev:amd64
ii  libgrooveloudness4:amd64
ii  libgrooveplayer-dev:amd64
ii  libgrooveplayer4:amd64
ii  node-groove

I'd love if someone could help me with installing 1.5.1

**Comment by andrewrk** [comment]
I'm in the middle of a new libgroove release, but it's not done yet. I recommend using the latest *tagged* version of libgroove, and the latest master branch of groove basin.

**Comment by WouterLVV** [comment]
That helped, but it seems I fucked up my system/dependencies that it still wouldn't work.
Willl probably try again on a new linux install.

Thanks anyway!
