### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by jiawu** [andrewrk/groovebasin#487]
Hi there,

I'm trying to get the latest version (1.5.1) to work on an Rpi, but I fail at npm start. I'm building groovebasin and libgroove from source. Can I get some help here?

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
> 2 info using npm@2.14.2
> 3 info using node@v4.0.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info prestart groovebasin@1.5.1
> 6 info start groovebasin@1.5.1
> 7 verbose unsafe-perm in lifecycle true
> 8 info groovebasin@1.5.1 Failed to exec start script
> 9 verbose stack Error: groovebasin@1.5.1 start: `node lib/server.js`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at EventEmitter.emit (events.js:172:7)
> 9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 9 verbose stack     at emitTwo (events.js:87:13)
> 9 verbose stack     at ChildProcess.emit (events.js:172:7)
> 9 verbose stack     at maybeClose (internal/child_process.js:817:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 10 verbose pkgid groovebasin@1.5.1
> 11 verbose cwd /home/jia/groovebasin
> 12 error Linux 4.1.19+
> 13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
> 14 error node v4.0.0
> 15 error npm  v2.14.2
> 16 error code ELIFECYCLE
> 17 error groovebasin@1.5.1 start: `node lib/server.js`
> 17 error Exit status 1
> 18 error Failed at the groovebasin@1.5.1 start script 'node lib/server.js'.
> 18 error This is most likely a problem with the groovebasin package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     node lib/server.js
> 18 error You can get their info via:
> 18 error     npm owner ls groovebasin
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

**Comment by rbrenner87** [comment]
You ever find a solution? I am having similar error at npm start on my ubuntu vps, although I am running node v0.12.10 vs your v4.0.0.
