### ISSUE TITLE
npm build errors on rpi

### ISSUE THREAD

**Issue by htmlboss** [andrewrk/groovebasin#491]
I followed your tutorial: [http://andrewkelley.me/post/raspberry-pi-music-player-server.html](http://andrewkelley.me/post/raspberry-pi-music-player-server.html)

And I have nodejs 0.10.29 installed so here are the errors:
`pi@raspberrypi:~/groovebasin $ npm run build

> groovebasin@1.5.1 build /home/pi/groovebasin
> npm install && ./build

> groove@2.5.0 install /home/pi/groovebasin/node_modules/groove
> node-gyp rebuild

make: Entering directory '/home/pi/groovebasin/node_modules/groove/build'
  CXX(target) Release/obj.target/groove/src/groove.o
  CXX(target) Release/obj.target/groove/src/file.o
../src/file.cc: In function ‘void OpenAfter(uv_work_t*)’:
../src/file.cc:238:17: error: no match for ‘operator=’ (operand types are ‘v8::Local<v8::Value>’ and ‘v8::Handle<v8::Value>’)
         argv[1] = GNFile::NewInstance(r->file);
                 ^
../src/file.cc:238:17: note: candidate is:
In file included from /home/pi/.node-gyp/0.10.29/src/node.h:62:0,
                 from ../src/file.cc:1:
/home/pi/.node-gyp/0.10.29/deps/v8/include/v8.h:269:26: note: v8::Local<v8::Value>& v8::Local<v8::Value>::operator=(const v8::Local<v8::Value>&)
 template <class T> class Local : public Handle<T> {
                          ^
/home/pi/.node-gyp/0.10.29/deps/v8/include/v8.h:269:26: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>’ to ‘const v8::Local<v8::Value>&’
groove.target.mk:89: recipe for target 'Release/obj.target/groove/src/file.o' failed
make: *** [Release/obj.target/groove/src/file.o] Error 1
make: Leaving directory '/home/pi/groovebasin/node_modules/groove/build'
 build error
 Error: `make` failed with exit code: 2
 stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
     at ChildProcess.emit (events.js:98:17)
 stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
 System Linux 4.1.19+
 ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
ERR! cwd /home/pi/groovebasin/node_modules/groove
 ERR! node -v v0.10.29
 node-gyp -v v0.13.1
ERR! not ok
ERR! groove@2.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
 pm ERR!\
npm ERR! Failed at the groove@2.5.0 install script.
npm ERR! This is most likely a problem with the groove package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls groove
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.19+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/pi/groovebasin
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
ERR!     /home/pi/groovebasin/npm-debug.log
npm ERR! not ok code 0
\
npm ERR! groovebasin@1.5.1 build: `npm install && ./build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the groovebasin@1.5.1 build script.
npm ERR! This is most likely a problem with the groovebasin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && ./build
npm ERR! You can get their info via:
npm ERR!     npm owner ls groovebasin
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.19+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! cwd /home/pi/groovebasin
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/groovebasin/npm-debug.log
npm ERR! not ok code 0
`

Any ideas?

**Comment by jon3654** [comment]
Nope, I have a similar issue. I have libgroove 4.3 and node 0.12.10 installed, and I was trying to install the latest release from source.
