### ISSUE TITLE
It would be awesome if your project got some love again.  

### ISSUE THREAD

**Issue by raksasas** [andrewrk/groovebasin#517]
@andrewrk 

Hello again, 
Looks like some time has passed. It would be awesome if your project got some love again.  

My original vm running this thing took a dump on me.  While trying to rebuild it with newer os's it seems to produce a ton of errors when "npm run build" is ran. 

Hoping you make it back around to this project. Especially for all of us that still prefer to own our music instead of relying on Spotify/Amazon Music, etc to keep it in there library for streaming

**Comment by raksasas** [comment]
looks to be the same errors - Debian & Ubuntu

```
groove@groovebasin:~$ git clone https://github.com/andrewrk/groovebasin.git
Cloning into 'groovebasin'...
remote: Enumerating objects: 8144, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8144 (delta 0), reused 0 (delta 0), pack-reused 8141
Receiving objects: 100% (8144/8144), 3.58 MiB | 3.63 MiB/s, done.
Resolving deltas: 100% (4653/4653), done.
groove@groovebasin:~$ cd groovebasin/
groove@groovebasin:~/groovebasin$ npm run build

> groovebasin@1.5.1 build /home/groove/groovebasin
> npm install && ./build

npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.54.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated request@2.74.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@2.3.1: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@1.8.0: this library is no longer supported
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> groove@2.5.1 install /home/groove/groovebasin/node_modules/groove
> node-gyp rebuild

make: Entering directory '/home/groove/groovebasin/node_modules/groove/build'
  CXX(target) Release/obj.target/groove/src/groove.o
In file included from ../../nan/nan.h:190,
                 from ../src/groove.cc:2:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:88:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   88 |   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
      |               ^~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:817:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  817 |         v8::Isolate::GetCurrent(), target, func, argc, argv);
      |                                                            ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h:817:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  817 |         v8::Isolate::GetCurrent(), target, func, argc, argv);
      |                                                            ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:831:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  831 |         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
      |                                                              ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:170:50: note: declared here
  170 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h:831:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  831 |         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
      |                                                              ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:170:50: note: declared here
  170 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:845:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  845 |         v8::Isolate::GetCurrent(), target, method, argc, argv);
      |                                                              ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:163:50: note: declared here
  163 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h:845:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
  845 |         v8::Isolate::GetCurrent(), target, method, argc, argv);
      |                                                              ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:163:50: note: declared here
  163 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1463:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
 1463 |     ));
      |     ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h:1463:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
 1463 |     ));
      |     ^
In file included from ../src/groove.cc:1:
/usr/include/nodejs/src/node.h:177:50: note: declared here
  177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
      |                                                  ^~~~~~~~~~~~
/usr/include/nodejs/src/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
   91 |     __attribute__((deprecated(message))) declarator
      |                                          ^~~~~~~~~~
In file included from ../src/groove.cc:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:1706:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 1706 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/groove.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE SetLogging(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/groove.cc:21:45: warning: ‘double v8::Value::NumberValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   21 |     groove_set_logging(info[0]->NumberValue());
      |                                             ^
In file included from /usr/include/nodejs/deps/v8/include/v8.h:26,
                 from /usr/include/nodejs/src/node.h:63,
                 from ../src/groove.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h:2475:45: note: declared here
 2475 |   V8_DEPRECATED("Use maybe version", double NumberValue() const);
      |                                             ^~~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
  324 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
In file included from ../src/groove.cc:1:
../src/groove.cc: At global scope:
/usr/include/nodejs/src/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  573 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/usr/include/nodejs/src/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
  607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/groove.cc:101:1: note: in expansion of macro ‘NODE_MODULE’
  101 | NODE_MODULE(groove, Initialize)
      | ^~~~~~~~~~~
In file included from /usr/include/nodejs/src/node.h:63,
                 from ../src/groove.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/usr/include/nodejs/src/node_object_wrap.h:84:78:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:66:61:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [groove.target.mk:110: Release/obj.target/groove/src/groove.o] Error 1
make: Leaving directory '/home/groove/groovebasin/node_modules/groove/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-89-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/groove/groovebasin/node_modules/groove
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! groove@2.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the groove@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/groove/.npm/_logs/2021-10-30T16_54_39_696Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! groovebasin@1.5.1 build: `npm install && ./build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the groovebasin@1.5.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/groove/.npm/_logs/2021-10-30T16_54_39_806Z-debug.log
```

**Comment by andrewrk** [comment]
oh it will. don't worry. I still use this software every single day, and we are on the brink of a renaissance.

**Comment by raksasas** [comment]
Looking forward to running this again... I haven't found a better solution...

**Comment by BrianGallew** [comment]
Same

**Comment by BrianGallew** [comment]
Also?  I'd love to know *how* you run this software every day.  I'm unable to build it, and all the docker images I've found for it fail to run it, either.

**Comment by raksasas** [comment]
@BrianGallew 

@andrewrk is the writer/owner of this project.  I presume he has become busy and it taking time away from this.

**Comment by andrewrk** [comment]
The love is coming soon, don't worry

**Comment by andrewrk** [comment]
For what it's worth, I still use this every day.

I have it working with node version `v8.10.0`, and the following nix environment:

```nix
with import <nixpkgs> {}; {
  groovebasinEnv = stdenv.mkDerivation {
    name = "groovebasin";
    buildInputs = [
      libsoundio
      libgroove
      python27Full
      gnumake
    ];

    shellHook = ''
      export PATH="/home/andy/local/bin:$PATH"
    '';
 
  };
}
```

@thejoshwolfe and I have already started rewriting it in zig (see the `zig` branch) and will pick it up in earnest as the zig standard library starts to support more web stuff.

**Comment by alexandrucancescu** [comment]
@andrewrk I would love to see groove be maintained again! Do you also plan to offer some love to node-libgroove?

**Comment by andrewrk** [comment]
no, node-libgroove is going to stay dead. someone will have to fork that if they want to keep using it.

libgroove will get some love, but we might transition away from using it.
